# Generated by Django 4.0.3 on 2022-03-28 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aufgabe',
            name='fachgebiet',
            field=models.TextField(blank=True, null=True),
        ),
    ]
